#!/usr/bin/env bash
set -uo pipefail

# Validate a player's disc copy against the manifest the game was recompiled from.
#
# Usage: ps2x-verify-disc.sh <game_dir> [--deep] [--quiet] [--write]
#
# Lives in the PS2Recomp fork (scripts/) since 2026-10-02 so every game built with this toolchain
# shares one copy; the game supplies the data (recomp/disc.manifest, recomp/config.toml).
#
#   (default)  ELF identity (size + sha256) + a presence/size sweep of every manifest
#              entry. Reads ~1.5 MB and stats the rest, so it is effectively free and
#              runs as a preflight from 02/03/04.
#   --deep     additionally sha256 EVERY data file. Definitive, but reads the whole
#              disc (~2.3 GB here). For "my game misbehaves, is my dump good?".
#   --quiet    print only on failure (preflight mode).
#   --write    (maintainer) regenerate <game_dir>/recomp/disc.manifest from the tree
#              that is present now. Only ever run this against a KNOWN-GOOD copy.
#
# WHY this exists: a static recompilation is tied to ONE exact executable. recomp/
# functions.csv is a list of addresses inside a specific ELF; point the build at a
# different region -- or a different revision of the same region -- and every one of
# those addresses lands somewhere else. The failure is not a clean error, it is
# garbage behaviour a long way from the cause. The check costs milliseconds; the
# confusion it prevents costs hours.
#
# Exit codes (so callers can distinguish, rather than just "it failed"):
#   0 ok   1 no disc files   2 wrong disc (region/revision)   3 incomplete
#   4 corrupt (size/hash)    5 cannot verify (no manifest)    64 usage error

GAME_DIR=""; DEEP=false; QUIET=false; WRITE=false
while [[ $# -gt 0 ]]; do
    case "$1" in
        --deep)  DEEP=true;  shift ;;
        --quiet) QUIET=true; shift ;;
        --write) WRITE=true; shift ;;
        -*) echo "ps2x-verify-disc.sh: unknown option: $1" >&2; exit 64 ;;
        *)  [[ -z "$GAME_DIR" ]] || { echo "ps2x-verify-disc.sh: unexpected argument: $1" >&2; exit 64; }
            GAME_DIR="$1"; shift ;;
    esac
done
[[ -n "$GAME_DIR" ]] || { echo "Usage: ps2x-verify-disc.sh <game_dir> [--deep] [--quiet] [--write]" >&2; exit 64; }
[[ -d "$GAME_DIR" ]] || { echo "ps2x-verify-disc.sh: game dir not found: $GAME_DIR" >&2; exit 64; }
GAME_DIR="$(cd "$GAME_DIR" && pwd)"

GF="$GAME_DIR/gamefiles"
MANIFEST="$GAME_DIR/recomp/disc.manifest"
CONFIG="$GAME_DIR/recomp/config.toml"

say()  { [[ "$QUIET" == true ]] || printf '%s\n' "$*"; }
fail() { printf '%s\n' "$*" >&2; }          # failures print even when --quiet

# Sony disc-serial prefixes -> the region that serial belongs to. This is the standard
# prefix convention, NOT a claim about any particular title: it lets a wrong dump say
# "that is an NTSC-U disc" instead of "unknown file", without inventing serials we have
# never seen. Anything unrecognised is reported as its literal serial and nothing more.
region_of() {
    case "${1:0:4}" in
        SLES|SCES)            echo "PAL" ;;
        SLUS|SCUS)            echo "NTSC-U" ;;
        SLPS|SLPM|SCPS|SCPM)  echo "NTSC-J" ;;
        SLKA|SCKA)            echo "NTSC-K" ;;
        SLAJ|SCAJ)            echo "NTSC-J/Asia" ;;
        *)                    echo "" ;;
    esac
}

# The ELF this build was recompiled from, as the config declares it.
elf_rel_from_config() {
    [[ -f "$CONFIG" ]] || return 1
    grep -E "^[[:space:]]*input[[:space:]]*=" "$CONFIG" | head -1 | sed -E 's/.*=[[:space:]]*"([^"]+)".*/\1/'
}

# ---------------------------------------------------------------------------------
# --write: regenerate the manifest from the tree that is here now
# ---------------------------------------------------------------------------------
if [[ "$WRITE" == true ]]; then
    [[ -d "$GF" ]] || { fail "ps2x-verify-disc.sh --write: no gamefiles/ to read: $GF"; exit 1; }
    ELF_REL="$(elf_rel_from_config)" || { fail "ps2x-verify-disc.sh --write: cannot read 'input' from $CONFIG"; exit 64; }
    ELF_ABS="$GAME_DIR/${ELF_REL#./}"
    [[ -f "$ELF_ABS" ]] || { fail "ps2x-verify-disc.sh --write: ELF not found: $ELF_ABS"; exit 1; }
    SERIAL="$(basename "$ELF_ABS")"

    echo "Hashing $(find "$GF" -type f | wc -l) files under $GF ..." >&2
    tmp="$(mktemp)"
    {
        echo "# Disc manifest for $(basename "$GAME_DIR") -- what this build was recompiled from."
        echo "#"
        echo "# Generated by ps2x-verify-disc.sh --write on $(date -u +%Y-%m-%d)."
        echo "# Checked by the same script from 02_verify_setup.sh / 03_build_game.sh / 04_run_game.sh."
        echo "#"
        echo "# This file describes a disc; it contains NO game content. Sizes and one-way hashes"
        echo "# of files the player supplies themselves -- the same thing preservation databases"
        echo "# publish openly -- so it is safe to commit while the disc itself never is."
        echo "#"
        echo "#   serial <id>              the boot executable's name = the disc's identity"
        echo "#   elf    <size> <sha256> <path relative to game dir>"
        echo "#   file   <size> <sha256> <path relative to game dir>"
        echo "serial $SERIAL"
        printf 'elf    %s %s %s\n' \
            "$(stat -Lc%s "$ELF_ABS")" "$(sha256sum "$ELF_ABS" | cut -d' ' -f1)" "${ELF_REL#./}"
        # Every other file, ELF excluded (it has its own line), sorted for a stable diff.
        # Two things are deliberately NOT described here, because a genuine disc copy will
        # not have them and listing them would report a good copy as incomplete:
        #   - dotfiles (.gitkeep and friends) -- this repo's bookkeeping, not disc content
        #   - mc0/, mc1/  -- memory cards, i.e. the PLAYER's saves, written by the runtime
        while IFS= read -r rel; do
            [[ "gamefiles/$rel" == "${ELF_REL#./}" ]] && continue
            printf 'file   %s %s %s\n' \
                "$(stat -Lc%s "$GF/$rel")" "$(sha256sum "$GF/$rel" | cut -d' ' -f1)" "gamefiles/$rel"
        done < <(find -L "$GF" -type f -printf '%P\n' \
                 | grep -vE '(^|/)\.' \
                 | grep -vE '^mc[0-9]+/' \
                 | LC_ALL=C sort)
    } > "$tmp"
    mkdir -p "$(dirname "$MANIFEST")"
    mv "$tmp" "$MANIFEST"
    chmod 0644 "$MANIFEST"        # mktemp makes 0600; this file gets committed
    echo "Wrote $MANIFEST ($(grep -cE '^(elf|file) ' "$MANIFEST") entries)." >&2
    exit 0
fi

# ---------------------------------------------------------------------------------
# Verify
# ---------------------------------------------------------------------------------
say "Disc check: $GF"

# NB every size read below is `stat -Lc%s`, dereferencing. GNU stat does NOT follow a
# symlink by default, but `[[ -f ]]` and sha256sum both do -- so plain `-c%s` would size
# the LINK while the other two checks read its target, and a player who points gamefiles/
# at a mounted image gets "wrong size, found 78" (the length of the target path).

# --- 1. Is there a disc copy at all? ---------------------------------------------
if [[ ! -d "$GF" ]] || [[ -z "$(ls -A "$GF" 2>/dev/null)" ]]; then
    fail ""
    fail "  [FAIL] No disc files found."
    fail "         expected: $GF/"
    fail ""
    fail "  This folder is where you copy the contents of your own PS2 disc -- all of it,"
    fail "  from the disc root: the DATA/ and MODULES/ folders, SYSTEM.CNF, and the boot"
    fail "  executable next to them. No game data ships with this project."
    exit 1
fi

# --- 2. Do we have something to check against? ------------------------------------
if [[ ! -f "$MANIFEST" ]]; then
    fail "  [WARN] No disc manifest ($MANIFEST) -- cannot verify this copy."
    fail "         A maintainer creates one with: ps2x-verify-disc.sh <game_dir> --write"
    exit 5
fi

EXP_SERIAL="$(awk '$1=="serial"{print $2; exit}' "$MANIFEST")"
EXP_REGION="$(region_of "$EXP_SERIAL")"

# --- 3. What disc is actually here? ------------------------------------------------
# SYSTEM.CNF is the disc's own self-description (BOOT2 = cdrom0:\<SERIAL>;1). Prefer it,
# because it identifies the dump even when the executable itself was not copied -- which
# is exactly the case we most want to name precisely.
GOT_SERIAL=""
if [[ -f "$GF/SYSTEM.CNF" ]]; then
    GOT_SERIAL="$(sed -nE 's/.*BOOT2[[:space:]]*=[[:space:]]*cdrom0:\\?([^;[:space:]]+).*/\1/p' "$GF/SYSTEM.CNF" | head -1)"
fi
if [[ -z "$GOT_SERIAL" ]]; then   # no SYSTEM.CNF: fall back to a root file shaped like a serial
    GOT_SERIAL="$(find "$GF" -maxdepth 1 -type f -printf '%P\n' 2>/dev/null \
                  | grep -E '^S[CL][A-Z]{2}_[0-9]{3}\.[0-9]{2}$' | head -1)"
fi
GOT_REGION="$(region_of "$GOT_SERIAL")"

if [[ -n "$GOT_SERIAL" && -n "$EXP_SERIAL" && "$GOT_SERIAL" != "$EXP_SERIAL" ]]; then
    fail ""
    fail "  [FAIL] Wrong disc."
    fail "         this build is  $EXP_SERIAL${EXP_REGION:+  ($EXP_REGION)}"
    fail "         your copy is   $GOT_SERIAL${GOT_REGION:+  ($GOT_REGION)}"
    fail ""
    fail "  A static recompilation is tied to one exact executable: recomp/functions.csv is a"
    fail "  list of addresses inside it. Another region is a different build of the game, so"
    fail "  every one of those addresses points somewhere else. This is not something a"
    fail "  setting can bridge -- it needs the $EXP_SERIAL${EXP_REGION:+ ($EXP_REGION)} disc."
    exit 2
fi

# --- 4. The executable: present, and the right bytes? ------------------------------
read -r EXP_ELF_SIZE EXP_ELF_HASH EXP_ELF_REL < <(awk '$1=="elf"{print $2, $3, $4; exit}' "$MANIFEST")
ELF_ABS="$GAME_DIR/$EXP_ELF_REL"

if [[ ! -f "$ELF_ABS" ]]; then
    fail ""
    fail "  [FAIL] The disc data is here, but the boot executable is missing."
    fail "         expected: $ELF_ABS"
    fail ""
    if [[ -n "$GOT_SERIAL" ]]; then
        fail "  SYSTEM.CNF says this disc boots '$GOT_SERIAL', so the copy is the right disc --"
        fail "  the file just was not copied. Some tools skip it, or hide it as a system file."
    fi
    fail "  Copy the WHOLE disc root, not only the DATA/ folder."
    exit 3
fi

GOT_ELF_SIZE="$(stat -Lc%s "$ELF_ABS")"
if [[ "$GOT_ELF_SIZE" != "$EXP_ELF_SIZE" ]]; then
    fail ""
    fail "  [FAIL] The boot executable is the wrong size -- truncated, or a different build."
    fail "         expected $EXP_ELF_SIZE bytes, found $GOT_ELF_SIZE"
    fail "         $ELF_ABS"
    exit 4
fi

GOT_ELF_HASH="$(sha256sum "$ELF_ABS" | cut -d' ' -f1)"
if [[ "$GOT_ELF_HASH" != "$EXP_ELF_HASH" ]]; then
    fail ""
    fail "  [FAIL] The boot executable is not the one this build was made from."
    fail "         serial   $EXP_SERIAL (matches), size $GOT_ELF_SIZE (matches)"
    fail "         expected sha256 $EXP_ELF_HASH"
    fail "         found    sha256 $GOT_ELF_HASH"
    fail ""
    fail "  Same serial and same size but different bytes means a different revision of the"
    fail "  disc, or a damaged copy. Re-copy from the disc; if it still differs, this build"
    fail "  does not cover your revision."
    exit 4
fi
say "  [ OK ] executable  $EXP_SERIAL${EXP_REGION:+ ($EXP_REGION)}  $EXP_ELF_SIZE bytes, sha256 matches"

# --- 5. Every other file: present, right size (and on --deep, right bytes) ----------
MISSING=(); WRONGSIZE=(); WRONGHASH=(); NFILES=0
while read -r _kind size hash rel; do
    NFILES=$((NFILES + 1))
    p="$GAME_DIR/$rel"
    if [[ ! -f "$p" ]]; then MISSING+=("$rel"); continue; fi
    got="$(stat -Lc%s "$p")"
    if [[ "$got" != "$size" ]]; then WRONGSIZE+=("$rel (expected $size, found $got)"); continue; fi
    if [[ "$DEEP" == true ]]; then
        [[ "$(sha256sum "$p" | cut -d' ' -f1)" == "$hash" ]] || WRONGHASH+=("$rel")
    fi
done < <(awk '$1=="file"{print}' "$MANIFEST")

if [[ ${#MISSING[@]} -gt 0 ]]; then
    fail ""
    fail "  [FAIL] ${#MISSING[@]} of $NFILES file(s) are missing from your disc copy:"
    printf '           %s\n' "${MISSING[@]:0:12}" >&2
    [[ ${#MISSING[@]} -gt 12 ]] && fail "           ... and $((${#MISSING[@]} - 12)) more"
    fail ""
    fail "  The copy is incomplete. Copy the whole disc; if your tool stopped partway it may"
    fail "  have hit a read error on the disc itself."
    exit 3
fi
if [[ ${#WRONGSIZE[@]} -gt 0 ]]; then
    fail ""
    fail "  [FAIL] ${#WRONGSIZE[@]} of $NFILES file(s) are the wrong size -- truncated or corrupt:"
    printf '           %s\n' "${WRONGSIZE[@]:0:12}" >&2
    [[ ${#WRONGSIZE[@]} -gt 12 ]] && fail "           ... and $((${#WRONGSIZE[@]} - 12)) more"
    fail ""
    fail "  Re-copy these from the disc. A file that stops short is usually a read error."
    exit 4
fi
if [[ ${#WRONGHASH[@]} -gt 0 ]]; then
    fail ""
    fail "  [FAIL] ${#WRONGHASH[@]} of $NFILES file(s) have the right size but the wrong contents:"
    printf '           %s\n' "${WRONGHASH[@]:0:12}" >&2
    [[ ${#WRONGHASH[@]} -gt 12 ]] && fail "           ... and $((${#WRONGHASH[@]} - 12)) more"
    fail ""
    fail "  A right-sized file with wrong bytes is a bad read that the copying tool did not"
    fail "  notice. Re-copy these files."
    exit 4
fi

if [[ "$DEEP" == true ]]; then
    say "  [ OK ] data files  $NFILES/$NFILES present, correct size, sha256 verified"
    say "Disc verified (deep)."
else
    say "  [ OK ] data files  $NFILES/$NFILES present and the expected size"
    say "Disc verified.  (--deep also checksums every file)"
fi
exit 0
