#!/bin/bash
# ps2x-iop-native.sh -- sourced by ps2x-build-game.sh (rotk rows 275-276).
#
# gen_iop_native <game_dir> <config.toml> <disc_dir> <out_dir>
#   Statically recompile the IOP modules (IRX) a game lists in its config.toml [iop_native] section:
#
#     [iop_native]
#     "MODULES/AUDIOPF.IRX" = 0x54700     # path relative to the disc root (the ELF's folder) = IOP load base
#
#   Each module is placed and relocated at its base by ps2xIOP's own loader (ps2x_irx_image), translated by ps2_recomp
#   in R3000 mode into <out_dir>, and listed in a generated module table (ps2x_iop_native_modules.cpp) that the runtime
#   matches loaded modules against (file hash + base); a module loaded at another base stays interpreted. Used only when
#   the game runs its own IRX on the emulated IOP with PS2X_IOP_NATIVE=1. No section (or an empty one) = <out_dir>
#   removed, nothing generated. Cached: regenerates only when the list, an IRX or a tool changed. Generated from the
#   player's disc; never committed.
#   Needs PS2RECOMP_ROOT (the toolchain clone). Returns non-zero on failure.
gen_iop_native() {
    local game="$1" config="$2" disc="$3" out="$4"
    local work="$out.work"
    # The section's `"PATH" = 0xBASE` lines, as "PATH 0xBASE" (up to the next [section]).
    local list
    list=$(awk '/^\[/ { on = ($0 ~ /^\[iop_native\]/); next }
                on && /^[[:space:]]*"/ { gsub(/[" =]+/, " "); sub(/^ /, ""); sub(/[[:space:]]*#.*/, ""); print }' "$config")
    if [[ -z "$list" ]]; then
        rm -rf "$out" "$work"
        return 0
    fi
    local build="$PS2RECOMP_ROOT/out/build"
    local recomp="$build/ps2xRecomp/ps2_recomp" tool="$build/ps2xIOP/ps2x_irx_image"
    # A build tree configured before the tool existed has no such target yet: reconfigure it once and retry.
    cmake --build "$build" --target ps2x_irx_image -j"$(nproc)" >/dev/null 2>&1 ||
        { cmake "$build" >/dev/null && cmake --build "$build" --target ps2x_irx_image -j"$(nproc)" >/dev/null; } ||
        { echo "ERROR: building ps2x_irx_image failed"; return 1; }
    local stamp f b
    stamp=$({ echo "$list"
              while read -r f b; do sha1sum "$disc/$f"; done <<< "$list"
              sha1sum "$recomp" "$tool"; } | sha1sum | cut -c1-40)
    if [[ -f "$out/.stamp" && "$(cat "$out/.stamp")" == "$stamp" ]]; then
        echo "  IOP native modules: up to date"
        return 0
    fi
    rm -rf "$out" "$work"
    mkdir -p "$out" "$work"
    local decls="" adds="" stem ns reg info hash
    while read -r f b; do
        [[ -f "$disc/$f" ]] || { echo "ERROR: [iop_native] names $f, not found under $disc"; return 1; }
        stem="$(basename "${f%.*}")"
        ns="ps2x_iop_$(echo "$stem" | tr 'A-Z' 'a-z' | tr -c 'a-z0-9\n' '_')"
        reg="${ns/ps2x_iop_/ps2x_iop_register_}"
        info=$("$tool" "$disc/$f" "$b" "$work/$stem.elf") || { echo "ERROR: ps2x_irx_image $f $b: $info"; return 1; }
        hash=$(echo "$info" | grep -oE 'hash=0x[0-9a-f]+' | cut -d= -f2)
        cat > "$work/$stem.toml" <<TOML
[general]
input = "$work/$stem.elf"
output = "$out"
single_file_output = true
output_worker_thread = 1
patch_syscalls = false
patch_cop0 = false
patch_cache = false
arch = "r3000"
iop_namespace = "$ns"
iop_register = "$reg"
TOML
        "$recomp" "$work/$stem.toml" > "$work/$stem.log" 2>&1 ||
            { echo "ERROR: ps2_recomp failed on $f (see $work/$stem.log)"; return 1; }
        decls+="extern \"C\" void $reg(::ps2x::iop::native::Registry &);"$'\n'
        adds+="        ::ps2x::iop::native::addCompiledModule({\"$(basename "$f")\", ${hash}ull, ${b}u, &$reg});"$'\n'
        echo "  IOP native module: $f at $b ($ns)"
    done <<< "$list"
    cat > "$out/ps2x_iop_native_modules.cpp" <<CPP
// GENERATED by scripts/ps2x-iop-native.sh from the game's config.toml [iop_native]: the IOP modules this build
// recompiled, matched to a loaded IRX by its file hash and load base (ps2x::iop::native).
#include "ps2x_iop_native.h"

${decls}
namespace
{
struct Ps2xIopNativeModules
{
    Ps2xIopNativeModules()
    {
${adds}    }
} s_ps2xIopNativeModules;
}
CPP
    echo "$stamp" > "$out/.stamp"
}
